ci:
    autofix_prs: false
    autoupdate_schedule: monthly

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        args:
          - --fix
        files: '^custom_components/'
      - id: ruff-format
        files: '^custom_components/'
